### ISSUE TITLE
gtestTargets.cmake and gtestConfig.cmake missing

### ISSUE THREAD

**Issue by ukoethe** [conda-forge/gtest-feedstock#18]
These files should be installed into `$PREFIX/lib/cmake/gtest` in order to simplify configuration of gtest as a dependency in cmake files.

**Comment by SylvainCorlay** [comment]
Indeed, we should probably do a simple cmake install in `bld.bat` and `build.sh`.

**Comment by scopatz** [comment]
Prs welcome!

**Comment by SylvainCorlay** [comment]
So now, a `gtestConfig.cmake` should be installed. However, it will reflect whatever was the *last* build of gtest in the `build.sh`/ `bld.bat` since the shared libraries and static libraries are done with two different cmake builds...

I don't think that there is a means to have both in the same cmake build.

**Comment by wesm** [comment]
Would it be possible to create something like `gtest_staticConfig.cmake` manually?

**Comment by SylvainCorlay** [comment]
> Would it be possible to create something like `gtest_staticConfig.cmake` manually?

I guess we could have multiple cmake config files although a `find_package` might not be able to see it.
